name: snowflake-demo
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - pip:
    # Snowflake
    - snowflake-cli-labs==0.2.9
    - snowflake-snowpark-python==3.1.1
